<input type="hidden" id="POOL_NAME" name="POOL_NAME" value="pool"/>
<input type="hidden" name="emailCount" value="${EMAIL_ABANDON_NUM!""}" />
<input type="hidden" name="intervalHours" value="${EMAIL_ABANDON_HRS!""}" />
<input type="hidden" name="feedsInRatingDir" value="${FEEDS_IN_RATING_URL_DIR!""}" />
<input type="hidden" name="feedsInProductDir" value="${FEEDS_IN_PRODUCT_URL_DIR!""}" />
<input type="hidden" name="feedsInOrderStatusDir" value="${FEEDS_IN_ORDER_STATUS_URL_DIR!""}" />
<input type="hidden" name="feedsInStoreDir" value="${FEEDS_IN_STORE_URL_DIR!""}" />
<input type="hidden" name="feedsInSuccessSubDir" value="${FEEDS_IN_SUCCESS_SUB_DIR!""}" />
<input type="hidden" name="feedsInErrorSubDir" value="${FEEDS_IN_ERROR_SUB_DIR!""}" />
<input type="hidden" name="feedsOutCustomerDir" value="${FEEDS_OUT_CUSTOMER_URL_DIR!""}" />
<input type="hidden" name="feedsOutCustomerPrefix" value="${FEEDS_OUT_CUSTOMER_PREFIX!""}" />
<input type="hidden" name="feedsOutOrderDir" value="${FEEDS_OUT_ORDER_URL_DIR!""}" />
<input type="hidden" name="feedsOutOrderPrefix" value="${FEEDS_OUT_ORDER_PREFIX!""}" />
<input type="hidden" name="feedsOutContactUsDir" value="${FEEDS_OUT_CONTACT_US_URL_DIR!""}" />
<input type="hidden" name="feedsOutContactUsPrefix" value="${FEEDS_OUT_CONTACT_US_PREFIX!""}" />
<input type="hidden" name="feedsOutRequestCatalogDir" value="${FEEDS_OUT_REQUEST_CATALOG_URL_DIR!""}" />
<input type="hidden" name="feedsOutRequestCatalogPrefix" value="${FEEDS_OUT_REQUEST_CATALOG_PREFIX!""}" />
<input type="hidden" name="reevooApiUrl" value="${REEVOO_API_URL!""}" />
<input type="hidden" name="reevooApiCsvUrl" value="${REEVOO_CSV_URL!""}" />
<input type="hidden" name="reevooApiUserName" value="${REEVOO_USERNAME!""}" />
<input type="hidden" name="reevooApiPassword" value="${REEVOO_PASSWORD!""}" />