//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.25 at 12:42:51 AM CST 
//


package com.osafe.feeds.osafefeeds;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.osafe.feeds.osafefeeds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BigFishStoreFeed_QNAME = new QName("", "BigFishStoreFeed");
    private final static QName _BigFishOrderFeed_QNAME = new QName("", "BigFishOrderFeed");
    private final static QName _ThruDate_QNAME = new QName("", "ThruDate");
    private final static QName _BigFishRequestCatalogFeed_QNAME = new QName("", "BigFishRequestCatalogFeed");
    private final static QName _Url_QNAME = new QName("", "Url");
    private final static QName _BigFishContactUsFeed_QNAME = new QName("", "BigFishContactUsFeed");
    private final static QName _BigFishOrderStatusUpdateFeed_QNAME = new QName("", "BigFishOrderStatusUpdateFeed");
    private final static QName _BigFishCustomerFeed_QNAME = new QName("", "BigFishCustomerFeed");
    private final static QName _BigFishProductFeed_QNAME = new QName("", "BigFishProductFeed");
    private final static QName _BigFishProductRatingFeed_QNAME = new QName("", "BigFishProductRatingFeed");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.osafe.feeds.osafefeeds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BigFishStoreFeedType }
     * 
     */
    public BigFishStoreFeedType createBigFishStoreFeedType() {
        return new BigFishStoreFeedType();
    }

    /**
     * Create an instance of {@link BigFishOrderFeedType }
     * 
     */
    public BigFishOrderFeedType createBigFishOrderFeedType() {
        return new BigFishOrderFeedType();
    }

    /**
     * Create an instance of {@link BigFishRequestCatalogFeedType }
     * 
     */
    public BigFishRequestCatalogFeedType createBigFishRequestCatalogFeedType() {
        return new BigFishRequestCatalogFeedType();
    }

    /**
     * Create an instance of {@link BigFishContactUsFeedType }
     * 
     */
    public BigFishContactUsFeedType createBigFishContactUsFeedType() {
        return new BigFishContactUsFeedType();
    }

    /**
     * Create an instance of {@link BigFishOrderStatusUpdateFeedType }
     * 
     */
    public BigFishOrderStatusUpdateFeedType createBigFishOrderStatusUpdateFeedType() {
        return new BigFishOrderStatusUpdateFeedType();
    }

    /**
     * Create an instance of {@link BigFishProductRatingFeedType }
     * 
     */
    public BigFishProductRatingFeedType createBigFishProductRatingFeedType() {
        return new BigFishProductRatingFeedType();
    }

    /**
     * Create an instance of {@link BigFishProductFeedType }
     * 
     */
    public BigFishProductFeedType createBigFishProductFeedType() {
        return new BigFishProductFeedType();
    }

    /**
     * Create an instance of {@link BigFishCustomerFeedType }
     * 
     */
    public BigFishCustomerFeedType createBigFishCustomerFeedType() {
        return new BigFishCustomerFeedType();
    }

    /**
     * Create an instance of {@link FacetValueType }
     * 
     */
    public FacetValueType createFacetValueType() {
        return new FacetValueType();
    }

    /**
     * Create an instance of {@link ManufacturerAddressType }
     * 
     */
    public ManufacturerAddressType createManufacturerAddressType() {
        return new ManufacturerAddressType();
    }

    /**
     * Create an instance of {@link ProductFacetCatGroupType }
     * 
     */
    public ProductFacetCatGroupType createProductFacetCatGroupType() {
        return new ProductFacetCatGroupType();
    }

    /**
     * Create an instance of {@link PdpAdditionalLargeImageType }
     * 
     */
    public PdpAdditionalLargeImageType createPdpAdditionalLargeImageType() {
        return new PdpAdditionalLargeImageType();
    }

    /**
     * Create an instance of {@link ContactUsType }
     * 
     */
    public ContactUsType createContactUsType() {
        return new ContactUsType();
    }

    /**
     * Create an instance of {@link PlpImageType }
     * 
     */
    public PlpImageType createPlpImageType() {
        return new PlpImageType();
    }

    /**
     * Create an instance of {@link ProductInventoryType }
     * 
     */
    public ProductInventoryType createProductInventoryType() {
        return new ProductInventoryType();
    }

    /**
     * Create an instance of {@link FeatureType }
     * 
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link PdpVideoType }
     * 
     */
    public PdpVideoType createPdpVideoType() {
        return new PdpVideoType();
    }

    /**
     * Create an instance of {@link ManufacturerImageType }
     * 
     */
    public ManufacturerImageType createManufacturerImageType() {
        return new ManufacturerImageType();
    }

    /**
     * Create an instance of {@link PdpAdditionalDetailImageType }
     * 
     */
    public PdpAdditionalDetailImageType createPdpAdditionalDetailImageType() {
        return new PdpAdditionalDetailImageType();
    }

    /**
     * Create an instance of {@link ProductFacetValueType }
     * 
     */
    public ProductFacetValueType createProductFacetValueType() {
        return new ProductFacetValueType();
    }

    /**
     * Create an instance of {@link PdpSwatchType }
     * 
     */
    public PdpSwatchType createPdpSwatchType() {
        return new PdpSwatchType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link GoodIdentificationType }
     * 
     */
    public GoodIdentificationType createGoodIdentificationType() {
        return new GoodIdentificationType();
    }

    /**
     * Create an instance of {@link ManufacturerType }
     * 
     */
    public ManufacturerType createManufacturerType() {
        return new ManufacturerType();
    }

    /**
     * Create an instance of {@link RecurringPriceType }
     * 
     */
    public RecurringPriceType createRecurringPriceType() {
        return new RecurringPriceType();
    }

    /**
     * Create an instance of {@link ProductImageType }
     * 
     */
    public ProductImageType createProductImageType() {
        return new ProductImageType();
    }

    /**
     * Create an instance of {@link ProductCategoryType }
     * 
     */
    public ProductCategoryType createProductCategoryType() {
        return new ProductCategoryType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link ProductSelectableFeatureType }
     * 
     */
    public ProductSelectableFeatureType createProductSelectableFeatureType() {
        return new ProductSelectableFeatureType();
    }

    /**
     * Create an instance of {@link OrderLineAttributeType }
     * 
     */
    public OrderLineAttributeType createOrderLineAttributeType() {
        return new OrderLineAttributeType();
    }

    /**
     * Create an instance of {@link UserLoginType }
     * 
     */
    public UserLoginType createUserLoginType() {
        return new UserLoginType();
    }

    /**
     * Create an instance of {@link OrderStatusType }
     * 
     */
    public OrderStatusType createOrderStatusType() {
        return new OrderStatusType();
    }

    /**
     * Create an instance of {@link ShipmentType }
     * 
     */
    public ShipmentType createShipmentType() {
        return new ShipmentType();
    }

    /**
     * Create an instance of {@link PaymentGatewayResponseType }
     * 
     */
    public PaymentGatewayResponseType createPaymentGatewayResponseType() {
        return new PaymentGatewayResponseType();
    }

    /**
     * Create an instance of {@link ProductManufacturerType }
     * 
     */
    public ProductManufacturerType createProductManufacturerType() {
        return new ProductManufacturerType();
    }

    /**
     * Create an instance of {@link PdpLargeImageType }
     * 
     */
    public PdpLargeImageType createPdpLargeImageType() {
        return new PdpLargeImageType();
    }

    /**
     * Create an instance of {@link RequestCatalogType }
     * 
     */
    public RequestCatalogType createRequestCatalogType() {
        return new RequestCatalogType();
    }

    /**
     * Create an instance of {@link PdpAlternateImageType }
     * 
     */
    public PdpAlternateImageType createPdpAlternateImageType() {
        return new PdpAlternateImageType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link AssociationType }
     * 
     */
    public AssociationType createAssociationType() {
        return new AssociationType();
    }

    /**
     * Create an instance of {@link OrderLineType }
     * 
     */
    public OrderLineType createOrderLineType() {
        return new OrderLineType();
    }

    /**
     * Create an instance of {@link OrderAdjustmentType }
     * 
     */
    public OrderAdjustmentType createOrderAdjustmentType() {
        return new OrderAdjustmentType();
    }

    /**
     * Create an instance of {@link ProductAttachmentsType }
     * 
     */
    public ProductAttachmentsType createProductAttachmentsType() {
        return new ProductAttachmentsType();
    }

    /**
     * Create an instance of {@link PlpSmallAltImageType }
     * 
     */
    public PlpSmallAltImageType createPlpSmallAltImageType() {
        return new PlpSmallAltImageType();
    }

    /**
     * Create an instance of {@link ProductAssociationType }
     * 
     */
    public ProductAssociationType createProductAssociationType() {
        return new ProductAssociationType();
    }

    /**
     * Create an instance of {@link CustomProductAttributeType }
     * 
     */
    public CustomProductAttributeType createCustomProductAttributeType() {
        return new CustomProductAttributeType();
    }

    /**
     * Create an instance of {@link ProductRatingType }
     * 
     */
    public ProductRatingType createProductRatingType() {
        return new ProductRatingType();
    }

    /**
     * Create an instance of {@link OrderShipmentType }
     * 
     */
    public OrderShipmentType createOrderShipmentType() {
        return new OrderShipmentType();
    }

    /**
     * Create an instance of {@link OrderPaymentType }
     * 
     */
    public OrderPaymentType createOrderPaymentType() {
        return new OrderPaymentType();
    }

    /**
     * Create an instance of {@link PaymentType }
     * 
     */
    public PaymentType createPaymentType() {
        return new PaymentType();
    }

    /**
     * Create an instance of {@link ProductCategoryMemberType }
     * 
     */
    public ProductCategoryMemberType createProductCategoryMemberType() {
        return new ProductCategoryMemberType();
    }

    /**
     * Create an instance of {@link ProductAttributeType }
     * 
     */
    public ProductAttributeType createProductAttributeType() {
        return new ProductAttributeType();
    }

    /**
     * Create an instance of {@link OrderLineItemsType }
     * 
     */
    public OrderLineItemsType createOrderLineItemsType() {
        return new OrderLineItemsType();
    }

    /**
     * Create an instance of {@link PdpAdditionalImageType }
     * 
     */
    public PdpAdditionalImageType createPdpAdditionalImageType() {
        return new PdpAdditionalImageType();
    }

    /**
     * Create an instance of {@link ListPriceType }
     * 
     */
    public ListPriceType createListPriceType() {
        return new ListPriceType();
    }

    /**
     * Create an instance of {@link OrderLineSalesTaxType }
     * 
     */
    public OrderLineSalesTaxType createOrderLineSalesTaxType() {
        return new OrderLineSalesTaxType();
    }

    /**
     * Create an instance of {@link PlpSmallImageType }
     * 
     */
    public PlpSmallImageType createPlpSmallImageType() {
        return new PlpSmallImageType();
    }

    /**
     * Create an instance of {@link OrderAttributeType }
     * 
     */
    public OrderAttributeType createOrderAttributeType() {
        return new OrderAttributeType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link StoreAddressType }
     * 
     */
    public StoreAddressType createStoreAddressType() {
        return new StoreAddressType();
    }

    /**
     * Create an instance of {@link PdpThumbnailImageType }
     * 
     */
    public PdpThumbnailImageType createPdpThumbnailImageType() {
        return new PdpThumbnailImageType();
    }

    /**
     * Create an instance of {@link OrderLinePromotionType }
     * 
     */
    public OrderLinePromotionType createOrderLinePromotionType() {
        return new OrderLinePromotionType();
    }

    /**
     * Create an instance of {@link PdpDetailImageType }
     * 
     */
    public PdpDetailImageType createPdpDetailImageType() {
        return new PdpDetailImageType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link StoreType }
     * 
     */
    public StoreType createStoreType() {
        return new StoreType();
    }

    /**
     * Create an instance of {@link OrderItemType }
     * 
     */
    public OrderItemType createOrderItemType() {
        return new OrderItemType();
    }

    /**
     * Create an instance of {@link FacetGroupType }
     * 
     */
    public FacetGroupType createFacetGroupType() {
        return new FacetGroupType();
    }

    /**
     * Create an instance of {@link OrderHeaderType }
     * 
     */
    public OrderHeaderType createOrderHeaderType() {
        return new OrderHeaderType();
    }

    /**
     * Create an instance of {@link ProductAttachType }
     * 
     */
    public ProductAttachType createProductAttachType() {
        return new ProductAttachType();
    }

    /**
     * Create an instance of {@link ProductDescriptiveFeatureType }
     * 
     */
    public ProductDescriptiveFeatureType createProductDescriptiveFeatureType() {
        return new ProductDescriptiveFeatureType();
    }

    /**
     * Create an instance of {@link FacetCatGroupType }
     * 
     */
    public FacetCatGroupType createFacetCatGroupType() {
        return new FacetCatGroupType();
    }

    /**
     * Create an instance of {@link PlpSwatchType }
     * 
     */
    public PlpSwatchType createPlpSwatchType() {
        return new PlpSwatchType();
    }

    /**
     * Create an instance of {@link CategoryMemberType }
     * 
     */
    public CategoryMemberType createCategoryMemberType() {
        return new CategoryMemberType();
    }

    /**
     * Create an instance of {@link BillingAddressType }
     * 
     */
    public BillingAddressType createBillingAddressType() {
        return new BillingAddressType();
    }

    /**
     * Create an instance of {@link ShippingAddressType }
     * 
     */
    public ShippingAddressType createShippingAddressType() {
        return new ShippingAddressType();
    }

    /**
     * Create an instance of {@link CustomerAttributeType }
     * 
     */
    public CustomerAttributeType createCustomerAttributeType() {
        return new CustomerAttributeType();
    }

    /**
     * Create an instance of {@link PdpAdditionalThumbImageType }
     * 
     */
    public PdpAdditionalThumbImageType createPdpAdditionalThumbImageType() {
        return new PdpAdditionalThumbImageType();
    }

    /**
     * Create an instance of {@link PdpVideo360Type }
     * 
     */
    public PdpVideo360Type createPdpVideo360Type() {
        return new PdpVideo360Type();
    }

    /**
     * Create an instance of {@link ProductAttributesType }
     * 
     */
    public ProductAttributesType createProductAttributesType() {
        return new ProductAttributesType();
    }

    /**
     * Create an instance of {@link GatewayResponseType }
     * 
     */
    public GatewayResponseType createGatewayResponseType() {
        return new GatewayResponseType();
    }

    /**
     * Create an instance of {@link AdjustmentType }
     * 
     */
    public AdjustmentType createAdjustmentType() {
        return new AdjustmentType();
    }

    /**
     * Create an instance of {@link ProductPriceType }
     * 
     */
    public ProductPriceType createProductPriceType() {
        return new ProductPriceType();
    }

    /**
     * Create an instance of {@link OrderLineShippingChargeType }
     * 
     */
    public OrderLineShippingChargeType createOrderLineShippingChargeType() {
        return new OrderLineShippingChargeType();
    }

    /**
     * Create an instance of {@link SalesPriceType }
     * 
     */
    public SalesPriceType createSalesPriceType() {
        return new SalesPriceType();
    }

    /**
     * Create an instance of {@link ShipGroupLineItemType }
     * 
     */
    public ShipGroupLineItemType createShipGroupLineItemType() {
        return new ShipGroupLineItemType();
    }

    /**
     * Create an instance of {@link ProductsType }
     * 
     */
    public ProductsType createProductsType() {
        return new ProductsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigFishStoreFeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigFishStoreFeed")
    public JAXBElement<BigFishStoreFeedType> createBigFishStoreFeed(BigFishStoreFeedType value) {
        return new JAXBElement<BigFishStoreFeedType>(_BigFishStoreFeed_QNAME, BigFishStoreFeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigFishOrderFeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigFishOrderFeed")
    public JAXBElement<BigFishOrderFeedType> createBigFishOrderFeed(BigFishOrderFeedType value) {
        return new JAXBElement<BigFishOrderFeedType>(_BigFishOrderFeed_QNAME, BigFishOrderFeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ThruDate", defaultValue = "")
    public JAXBElement<String> createThruDate(String value) {
        return new JAXBElement<String>(_ThruDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigFishRequestCatalogFeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigFishRequestCatalogFeed")
    public JAXBElement<BigFishRequestCatalogFeedType> createBigFishRequestCatalogFeed(BigFishRequestCatalogFeedType value) {
        return new JAXBElement<BigFishRequestCatalogFeedType>(_BigFishRequestCatalogFeed_QNAME, BigFishRequestCatalogFeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Url", defaultValue = "")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigFishContactUsFeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigFishContactUsFeed")
    public JAXBElement<BigFishContactUsFeedType> createBigFishContactUsFeed(BigFishContactUsFeedType value) {
        return new JAXBElement<BigFishContactUsFeedType>(_BigFishContactUsFeed_QNAME, BigFishContactUsFeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigFishOrderStatusUpdateFeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigFishOrderStatusUpdateFeed")
    public JAXBElement<BigFishOrderStatusUpdateFeedType> createBigFishOrderStatusUpdateFeed(BigFishOrderStatusUpdateFeedType value) {
        return new JAXBElement<BigFishOrderStatusUpdateFeedType>(_BigFishOrderStatusUpdateFeed_QNAME, BigFishOrderStatusUpdateFeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigFishCustomerFeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigFishCustomerFeed")
    public JAXBElement<BigFishCustomerFeedType> createBigFishCustomerFeed(BigFishCustomerFeedType value) {
        return new JAXBElement<BigFishCustomerFeedType>(_BigFishCustomerFeed_QNAME, BigFishCustomerFeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigFishProductFeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigFishProductFeed")
    public JAXBElement<BigFishProductFeedType> createBigFishProductFeed(BigFishProductFeedType value) {
        return new JAXBElement<BigFishProductFeedType>(_BigFishProductFeed_QNAME, BigFishProductFeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigFishProductRatingFeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigFishProductRatingFeed")
    public JAXBElement<BigFishProductRatingFeedType> createBigFishProductRatingFeed(BigFishProductRatingFeedType value) {
        return new JAXBElement<BigFishProductRatingFeedType>(_BigFishProductRatingFeed_QNAME, BigFishProductRatingFeedType.class, null, value);
    }

}
