//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.25 at 12:23:56 AM CST 
//


package com.osafe.feeds.osafefeeds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderLineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StatusId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SequenceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OfferPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsPromo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsModifiedPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LineTotalAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderLineSalesTax" type="{}OrderLineSalesTaxType" maxOccurs="unbounded"/>
 *         &lt;element name="OrderLineShippingCharge" type="{}OrderLineShippingChargeType" maxOccurs="unbounded"/>
 *         &lt;element name="OrderLinePromotion" type="{}OrderLinePromotionType" maxOccurs="unbounded"/>
 *         &lt;element name="OrderLineAttribute" type="{}OrderLineAttributeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderLineType", propOrder = {
    "statusId",
    "productId",
    "sequenceId",
    "quantity",
    "price",
    "listPrice",
    "offerPrice",
    "isPromo",
    "isModifiedPrice",
    "lineTotalAmount",
    "orderLineSalesTax",
    "orderLineShippingCharge",
    "orderLinePromotion",
    "orderLineAttribute"
})
public class OrderLineType {

    @XmlElement(name = "StatusId", required = true)
    protected String statusId;
    @XmlElement(name = "ProductId", required = true)
    protected String productId;
    @XmlElement(name = "SequenceId", required = true)
    protected String sequenceId;
    @XmlElement(name = "Quantity")
    protected int quantity;
    @XmlElement(name = "Price", required = true)
    protected String price;
    @XmlElement(name = "ListPrice", required = true)
    protected String listPrice;
    @XmlElement(name = "OfferPrice", required = true)
    protected String offerPrice;
    @XmlElement(name = "IsPromo", required = true)
    protected String isPromo;
    @XmlElement(name = "IsModifiedPrice", required = true)
    protected String isModifiedPrice;
    @XmlElement(name = "LineTotalAmount", required = true)
    protected String lineTotalAmount;
    @XmlElement(name = "OrderLineSalesTax", required = true)
    protected List<OrderLineSalesTaxType> orderLineSalesTax;
    @XmlElement(name = "OrderLineShippingCharge", required = true)
    protected List<OrderLineShippingChargeType> orderLineShippingCharge;
    @XmlElement(name = "OrderLinePromotion", required = true)
    protected List<OrderLinePromotionType> orderLinePromotion;
    @XmlElement(name = "OrderLineAttribute", required = true)
    protected OrderLineAttributeType orderLineAttribute;

    /**
     * Gets the value of the statusId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * Sets the value of the statusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusId(String value) {
        this.statusId = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the sequenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceId() {
        return sequenceId;
    }

    /**
     * Sets the value of the sequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceId(String value) {
        this.sequenceId = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the listPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListPrice() {
        return listPrice;
    }

    /**
     * Sets the value of the listPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListPrice(String value) {
        this.listPrice = value;
    }

    /**
     * Gets the value of the offerPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferPrice() {
        return offerPrice;
    }

    /**
     * Sets the value of the offerPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferPrice(String value) {
        this.offerPrice = value;
    }

    /**
     * Gets the value of the isPromo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPromo() {
        return isPromo;
    }

    /**
     * Sets the value of the isPromo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPromo(String value) {
        this.isPromo = value;
    }

    /**
     * Gets the value of the isModifiedPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsModifiedPrice() {
        return isModifiedPrice;
    }

    /**
     * Sets the value of the isModifiedPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsModifiedPrice(String value) {
        this.isModifiedPrice = value;
    }

    /**
     * Gets the value of the lineTotalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineTotalAmount() {
        return lineTotalAmount;
    }

    /**
     * Sets the value of the lineTotalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineTotalAmount(String value) {
        this.lineTotalAmount = value;
    }

    /**
     * Gets the value of the orderLineSalesTax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLineSalesTax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLineSalesTax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderLineSalesTaxType }
     * 
     * 
     */
    public List<OrderLineSalesTaxType> getOrderLineSalesTax() {
        if (orderLineSalesTax == null) {
            orderLineSalesTax = new ArrayList<OrderLineSalesTaxType>();
        }
        return this.orderLineSalesTax;
    }

    /**
     * Gets the value of the orderLineShippingCharge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLineShippingCharge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLineShippingCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderLineShippingChargeType }
     * 
     * 
     */
    public List<OrderLineShippingChargeType> getOrderLineShippingCharge() {
        if (orderLineShippingCharge == null) {
            orderLineShippingCharge = new ArrayList<OrderLineShippingChargeType>();
        }
        return this.orderLineShippingCharge;
    }

    /**
     * Gets the value of the orderLinePromotion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLinePromotion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLinePromotion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderLinePromotionType }
     * 
     * 
     */
    public List<OrderLinePromotionType> getOrderLinePromotion() {
        if (orderLinePromotion == null) {
            orderLinePromotion = new ArrayList<OrderLinePromotionType>();
        }
        return this.orderLinePromotion;
    }

    /**
     * Gets the value of the orderLineAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLineAttributeType }
     *     
     */
    public OrderLineAttributeType getOrderLineAttribute() {
        return orderLineAttribute;
    }

    /**
     * Sets the value of the orderLineAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLineAttributeType }
     *     
     */
    public void setOrderLineAttribute(OrderLineAttributeType value) {
        this.orderLineAttribute = value;
    }

}
