//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.25 at 12:23:56 AM CST 
//


package com.osafe.feeds.osafefeeds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductAttributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductAttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="PdpSelectMultiVariant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PdpCheckoutGiftMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PdpQtyMin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PdpQtyMax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PdpQtyDefault" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PdpInStoreOnly" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductAttributeType", propOrder = {

})
public class ProductAttributeType {

    @XmlElement(name = "PdpSelectMultiVariant", defaultValue = "")
    protected String pdpSelectMultiVariant;
    @XmlElement(name = "PdpCheckoutGiftMessage", defaultValue = "")
    protected String pdpCheckoutGiftMessage;
    @XmlElement(name = "PdpQtyMin", defaultValue = "")
    protected String pdpQtyMin;
    @XmlElement(name = "PdpQtyMax", defaultValue = "")
    protected String pdpQtyMax;
    @XmlElement(name = "PdpQtyDefault", defaultValue = "")
    protected String pdpQtyDefault;
    @XmlElement(name = "PdpInStoreOnly", defaultValue = "")
    protected String pdpInStoreOnly;

    /**
     * Gets the value of the pdpSelectMultiVariant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdpSelectMultiVariant() {
        return pdpSelectMultiVariant;
    }

    /**
     * Sets the value of the pdpSelectMultiVariant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdpSelectMultiVariant(String value) {
        this.pdpSelectMultiVariant = value;
    }

    /**
     * Gets the value of the pdpCheckoutGiftMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdpCheckoutGiftMessage() {
        return pdpCheckoutGiftMessage;
    }

    /**
     * Sets the value of the pdpCheckoutGiftMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdpCheckoutGiftMessage(String value) {
        this.pdpCheckoutGiftMessage = value;
    }

    /**
     * Gets the value of the pdpQtyMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdpQtyMin() {
        return pdpQtyMin;
    }

    /**
     * Sets the value of the pdpQtyMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdpQtyMin(String value) {
        this.pdpQtyMin = value;
    }

    /**
     * Gets the value of the pdpQtyMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdpQtyMax() {
        return pdpQtyMax;
    }

    /**
     * Sets the value of the pdpQtyMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdpQtyMax(String value) {
        this.pdpQtyMax = value;
    }

    /**
     * Gets the value of the pdpQtyDefault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdpQtyDefault() {
        return pdpQtyDefault;
    }

    /**
     * Sets the value of the pdpQtyDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdpQtyDefault(String value) {
        this.pdpQtyDefault = value;
    }

    /**
     * Gets the value of the pdpInStoreOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdpInStoreOnly() {
        return pdpInStoreOnly;
    }

    /**
     * Sets the value of the pdpInStoreOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdpInStoreOnly(String value) {
        this.pdpInStoreOnly = value;
    }

}
