//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.25 at 12:23:56 AM CST 
//


package com.osafe.feeds.osafefeeds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserLoginType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserLoginType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UserEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UserIsSystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserLoginType", propOrder = {
    "userName",
    "password",
    "userEnabled",
    "userIsSystem"
})
public class UserLoginType {

    @XmlElement(name = "UserName", required = true, defaultValue = "")
    protected String userName;
    @XmlElement(name = "Password", required = true, defaultValue = "")
    protected String password;
    @XmlElement(name = "UserEnabled", required = true, defaultValue = "")
    protected String userEnabled;
    @XmlElement(name = "UserIsSystem", required = true, defaultValue = "")
    protected String userIsSystem;

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the userEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserEnabled() {
        return userEnabled;
    }

    /**
     * Sets the value of the userEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserEnabled(String value) {
        this.userEnabled = value;
    }

    /**
     * Gets the value of the userIsSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserIsSystem() {
        return userIsSystem;
    }

    /**
     * Sets the value of the userIsSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserIsSystem(String value) {
        this.userIsSystem = value;
    }

}
